<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['id' => 1, 'code' => 'US', 'name' => 'United States'],
            ['id' => 2, 'code' => 'CA', 'name' => 'Canada'],
            ['id' => 3, 'code' => 'AF', 'name' => 'Afghanistan'],
            ['id' => 4, 'code' => 'AL', 'name' => 'Albania'],
            ['id' => 5, 'code' => 'DZ', 'name' => 'Algeria'],
            ['id' => 6, 'code' => 'AS', 'name' => 'American Samoa'],
            ['id' => 7, 'code' => 'AD', 'name' => 'Andorra'],
            ['id' => 8, 'code' => 'AO', 'name' => 'Angola'],
            ['id' => 9, 'code' => 'AI', 'name' => 'Anguilla'],
            ['id' => 10, 'code' => 'AQ', 'name' => 'Antarctica'],
            ['id' => 11, 'code' => 'AG', 'name' => 'Antigua and/or Barbuda'],
            ['id' => 12, 'code' => 'AR', 'name' => 'Argentina'],
            ['id' => 13, 'code' => 'AM', 'name' => 'Armenia'],
            ['id' => 14, 'code' => 'AW', 'name' => 'Aruba'],
            ['id' => 15, 'code' => 'AU', 'name' => 'Australia'],
            ['id' => 16, 'code' => 'AT', 'name' => 'Austria'],
            ['id' => 17, 'code' => 'AZ', 'name' => 'Azerbaijan'],
            ['id' => 18, 'code' => 'BS', 'name' => 'Bahamas'],
            ['id' => 19, 'code' => 'BH', 'name' => 'Bahrain'],
            ['id' => 20, 'code' => 'BD', 'name' => 'Bangladesh'],
            ['id' => 21, 'code' => 'BB', 'name' => 'Barbados'],
            ['id' => 22, 'code' => 'BY', 'name' => 'Belarus'],
            ['id' => 23, 'code' => 'BE', 'name' => 'Belgium'],
            ['id' => 24, 'code' => 'BZ', 'name' => 'Belize'],
            ['id' => 25, 'code' => 'BJ', 'name' => 'Benin'],
            ['id' => 26, 'code' => 'BM', 'name' => 'Bermuda'],
            ['id' => 27, 'code' => 'BT', 'name' => 'Bhutan'],
            ['id' => 28, 'code' => 'BO', 'name' => 'Bolivia'],
            ['id' => 29, 'code' => 'BA', 'name' => 'Bosnia and Herzegovina'],
            ['id' => 30, 'code' => 'BW', 'name' => 'Botswana'],
            ['id' => 31, 'code' => 'BV', 'name' => 'Bouvet Island'],
            ['id' => 32, 'code' => 'BR', 'name' => 'Brazil'],
            ['id' => 33, 'code' => 'IO', 'name' => 'British lndian Ocean Territory'],
            ['id' => 34, 'code' => 'BN', 'name' => 'Brunei Darussalam'],
            ['id' => 35, 'code' => 'BG', 'name' => 'Bulgaria'],
            ['id' => 36, 'code' => 'BF', 'name' => 'Burkina Faso'],
            ['id' => 37, 'code' => 'BI', 'name' => 'Burundi'],
            ['id' => 38, 'code' => 'KH', 'name' => 'Cambodia'],
            ['id' => 39, 'code' => 'CM', 'name' => 'Cameroon'],
            ['id' => 40, 'code' => 'CV', 'name' => 'Cape Verde'],
            ['id' => 41, 'code' => 'KY', 'name' => 'Cayman Islands'],
            ['id' => 42, 'code' => 'CF', 'name' => 'Central African Republic'],
            ['id' => 43, 'code' => 'TD', 'name' => 'Chad'],
            ['id' => 44, 'code' => 'CL', 'name' => 'Chile'],
            ['id' => 45, 'code' => 'CN', 'name' => 'China'],
            ['id' => 46, 'code' => 'CX', 'name' => 'Christmas Island'],
            ['id' => 47, 'code' => 'CC', 'name' => 'Cocos (Keeling] Islands'],
            ['id' => 48, 'code' => 'CO', 'name' => 'Colombia'],
            ['id' => 49, 'code' => 'KM', 'name' => 'Comoros'],
            ['id' => 50, 'code' => 'CG', 'name' => 'Congo'],
            ['id' => 51, 'code' => 'CK', 'name' => 'Cook Islands'],
            ['id' => 52, 'code' => 'CR', 'name' => 'Costa Rica'],
            ['id' => 53, 'code' => 'HR', 'name' => 'Croatia (Hrvatska]'],
            ['id' => 54, 'code' => 'CU', 'name' => 'Cuba'],
            ['id' => 55, 'code' => 'CY', 'name' => 'Cyprus'],
            ['id' => 56, 'code' => 'CZ', 'name' => 'Czech Republic'],
            ['id' => 57, 'code' => 'CD', 'name' => 'Democratic Republic of Congo'],
            ['id' => 58, 'code' => 'DK', 'name' => 'Denmark'],
            ['id' => 59, 'code' => 'DJ', 'name' => 'Djibouti'],
            ['id' => 60, 'code' => 'DM', 'name' => 'Dominica'],
            ['id' => 61, 'code' => 'DO', 'name' => 'Dominican Republic'],
            ['id' => 62, 'code' => 'TP', 'name' => 'East Timor'],
            ['id' => 63, 'code' => 'EC', 'name' => 'Ecudaor'],
            ['id' => 64, 'code' => 'EG', 'name' => 'Egypt'],
            ['id' => 65, 'code' => 'SV', 'name' => 'El Salvador'],
            ['id' => 66, 'code' => 'GQ', 'name' => 'Equatorial Guinea'],
            ['id' => 67, 'code' => 'ER', 'name' => 'Eritrea'],
            ['id' => 68, 'code' => 'EE', 'name' => 'Estonia'],
            ['id' => 69, 'code' => 'ET', 'name' => 'Ethiopia'],
            ['id' => 70, 'code' => 'FK', 'name' => 'Falkland Islands (Malvinas]'],
            ['id' => 71, 'code' => 'FO', 'name' => 'Faroe Islands'],
            ['id' => 72, 'code' => 'FJ', 'name' => 'Fiji'],
            ['id' => 73, 'code' => 'FI', 'name' => 'Finland'],
            ['id' => 74, 'code' => 'FR', 'name' => 'France'],
            ['id' => 75, 'code' => 'FX', 'name' => 'France, Metropolitan'],
            ['id' => 76, 'code' => 'GF', 'name' => 'French Guiana'],
            ['id' => 77, 'code' => 'PF', 'name' => 'French Polynesia'],
            ['id' => 78, 'code' => 'TF', 'name' => 'French Southern Territories'],
            ['id' => 79, 'code' => 'GA', 'name' => 'Gabon'],
            ['id' => 80, 'code' => 'GM', 'name' => 'Gambia'],
            ['id' => 81, 'code' => 'GE', 'name' => 'Georgia'],
            ['id' => 82, 'code' => 'DE', 'name' => 'Germany'],
            ['id' => 83, 'code' => 'GH', 'name' => 'Ghana'],
            ['id' => 84, 'code' => 'GI', 'name' => 'Gibraltar'],
            ['id' => 85, 'code' => 'GR', 'name' => 'Greece'],
            ['id' => 86, 'code' => 'GL', 'name' => 'Greenland'],
            ['id' => 87, 'code' => 'GD', 'name' => 'Grenada'],
            ['id' => 88, 'code' => 'GP', 'name' => 'Guadeloupe'],
            ['id' => 89, 'code' => 'GU', 'name' => 'Guam'],
            ['id' => 90, 'code' => 'GT', 'name' => 'Guatemala'],
            ['id' => 91, 'code' => 'GN', 'name' => 'Guinea'],
            ['id' => 92, 'code' => 'GW', 'name' => 'Guinea-Bissau'],
            ['id' => 93, 'code' => 'GY', 'name' => 'Guyana'],
            ['id' => 94, 'code' => 'HT', 'name' => 'Haiti'],
            ['id' => 95, 'code' => 'HM', 'name' => 'Heard and Mc Donald Islands'],
            ['id' => 96, 'code' => 'HN', 'name' => 'Honduras'],
            ['id' => 97, 'code' => 'HK', 'name' => 'Hong Kong'],
            ['id' => 98, 'code' => 'HU', 'name' => 'Hungary'],
            ['id' => 99, 'code' => 'IS', 'name' => 'Iceland'],
            ['id' => 100, 'code' => 'IN', 'name' => 'India'],
            ['id' => 101, 'code' => 'ID', 'name' => 'Indonesia'],
            ['id' => 102, 'code' => 'IR', 'name' => 'Iran (Islamic Republic of]'],
            ['id' => 103, 'code' => 'IQ', 'name' => 'Iraq'],
            ['id' => 104, 'code' => 'IE', 'name' => 'Ireland'],
            ['id' => 105, 'code' => 'IL', 'name' => 'Israel'],
            ['id' => 106, 'code' => 'IT', 'name' => 'Italy'],
            ['id' => 107, 'code' => 'CI', 'name' => 'Ivory Coast'],
            ['id' => 108, 'code' => 'JM', 'name' => 'Jamaica'],
            ['id' => 109, 'code' => 'JP', 'name' => 'Japan'],
            ['id' => 110, 'code' => 'JO', 'name' => 'Jordan'],
            ['id' => 111, 'code' => 'KZ', 'name' => 'Kazakhstan'],
            ['id' => 112, 'code' => 'KE', 'name' => 'Kenya'],
            ['id' => 113, 'code' => 'KI', 'name' => 'Kiribati'],
            ['id' => 114, 'code' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of'],
            ['id' => 115, 'code' => 'KR', 'name' => 'Korea, Republic of'],
            ['id' => 116, 'code' => 'KW', 'name' => 'Kuwait'],
            ['id' => 117, 'code' => 'KG', 'name' => 'Kyrgyzstan'],
            ['id' => 118, 'code' => 'LA', 'name' => 'Lao People\'s Democratic Republic'],
            ['id' => 119, 'code' => 'LV', 'name' => 'Latvia'],
            ['id' => 120, 'code' => 'LB', 'name' => 'Lebanon'],
            ['id' => 121, 'code' => 'LS', 'name' => 'Lesotho'],
            ['id' => 122, 'code' => 'LR', 'name' => 'Liberia'],
            ['id' => 123, 'code' => 'LY', 'name' => 'Libyan Arab Jamahiriya'],
            ['id' => 124, 'code' => 'LI', 'name' => 'Liechtenstein'],
            ['id' => 125, 'code' => 'LT', 'name' => 'Lithuania'],
            ['id' => 126, 'code' => 'LU', 'name' => 'Luxembourg'],
            ['id' => 127, 'code' => 'MO', 'name' => 'Macau'],
            ['id' => 128, 'code' => 'MK', 'name' => 'Macedonia'],
            ['id' => 129, 'code' => 'MG', 'name' => 'Madagascar'],
            ['id' => 130, 'code' => 'MW', 'name' => 'Malawi'],
            ['id' => 131, 'code' => 'MY', 'name' => 'Malaysia'],
            ['id' => 132, 'code' => 'MV', 'name' => 'Maldives'],
            ['id' => 133, 'code' => 'ML', 'name' => 'Mali'],
            ['id' => 134, 'code' => 'MT', 'name' => 'Malta'],
            ['id' => 135, 'code' => 'MH', 'name' => 'Marshall Islands'],
            ['id' => 136, 'code' => 'MQ', 'name' => 'Martinique'],
            ['id' => 137, 'code' => 'MR', 'name' => 'Mauritania'],
            ['id' => 138, 'code' => 'MU', 'name' => 'Mauritius'],
            ['id' => 139, 'code' => 'TY', 'name' => 'Mayotte'],
            ['id' => 140, 'code' => 'MX', 'name' => 'Mexico'],
            ['id' => 141, 'code' => 'FM', 'name' => 'Micronesia, Federated States of'],
            ['id' => 142, 'code' => 'MD', 'name' => 'Moldova, Republic of'],
            ['id' => 143, 'code' => 'MC', 'name' => 'Monaco'],
            ['id' => 144, 'code' => 'MN', 'name' => 'Mongolia'],
            ['id' => 145, 'code' => 'MS', 'name' => 'Montserrat'],
            ['id' => 146, 'code' => 'MA', 'name' => 'Morocco'],
            ['id' => 147, 'code' => 'MZ', 'name' => 'Mozambique'],
            ['id' => 148, 'code' => 'MM', 'name' => 'Myanmar'],
            ['id' => 149, 'code' => 'NA', 'name' => 'Namibia'],
            ['id' => 150, 'code' => 'NR', 'name' => 'Nauru'],
            ['id' => 151, 'code' => 'NP', 'name' => 'Nepal'],
            ['id' => 152, 'code' => 'NL', 'name' => 'Netherlands'],
            ['id' => 153, 'code' => 'AN', 'name' => 'Netherlands Antilles'],
            ['id' => 154, 'code' => 'NC', 'name' => 'New Caledonia'],
            ['id' => 155, 'code' => 'NZ', 'name' => 'New Zealand'],
            ['id' => 156, 'code' => 'NI', 'name' => 'Nicaragua'],
            ['id' => 157, 'code' => 'NE', 'name' => 'Niger'],
            ['id' => 158, 'code' => 'NG', 'name' => 'Nigeria'],
            ['id' => 159, 'code' => 'NU', 'name' => 'Niue'],
            ['id' => 160, 'code' => 'NF', 'name' => 'Norfork Island'],
            ['id' => 161, 'code' => 'MP', 'name' => 'Northern Mariana Islands'],
            ['id' => 162, 'code' => 'NO', 'name' => 'Norway'],
            ['id' => 163, 'code' => 'OM', 'name' => 'Oman'],
            ['id' => 164, 'code' => 'PK', 'name' => 'Pakistan'],
            ['id' => 165, 'code' => 'PW', 'name' => 'Palau'],
            ['id' => 166, 'code' => 'PA', 'name' => 'Panama'],
            ['id' => 167, 'code' => 'PG', 'name' => 'Papua New Guinea'],
            ['id' => 168, 'code' => 'PY', 'name' => 'Paraguay'],
            ['id' => 169, 'code' => 'PE', 'name' => 'Peru'],
            ['id' => 170, 'code' => 'PH', 'name' => 'Philippines'],
            ['id' => 171, 'code' => 'PN', 'name' => 'Pitcairn'],
            ['id' => 172, 'code' => 'PL', 'name' => 'Poland'],
            ['id' => 173, 'code' => 'PT', 'name' => 'Portugal'],
            ['id' => 174, 'code' => 'PR', 'name' => 'Puerto Rico'],
            ['id' => 175, 'code' => 'QA', 'name' => 'Qatar'],
            ['id' => 176, 'code' => 'SS', 'name' => 'Republic of South Sudan'],
            ['id' => 177, 'code' => 'RE', 'name' => 'Reunion'],
            ['id' => 178, 'code' => 'RO', 'name' => 'Romania'],
            ['id' => 179, 'code' => 'RU', 'name' => 'Russian Federation'],
            ['id' => 180, 'code' => 'RW', 'name' => 'Rwanda'],
            ['id' => 181, 'code' => 'KN', 'name' => 'Saint Kitts and Nevis'],
            ['id' => 182, 'code' => 'LC', 'name' => 'Saint Lucia'],
            ['id' => 183, 'code' => 'VC', 'name' => 'Saint Vincent and the Grenadines'],
            ['id' => 184, 'code' => 'WS', 'name' => 'Samoa'],
            ['id' => 185, 'code' => 'SM', 'name' => 'San Marino'],
            ['id' => 186, 'code' => 'ST', 'name' => 'Sao Tome and Principe'],
            ['id' => 187, 'code' => 'SA', 'name' => 'Saudi Arabia'],
            ['id' => 188, 'code' => 'SN', 'name' => 'Senegal'],
            ['id' => 189, 'code' => 'RS', 'name' => 'Serbia'],
            ['id' => 190, 'code' => 'SC', 'name' => 'Seychelles'],
            ['id' => 191, 'code' => 'SL', 'name' => 'Sierra Leone'],
            ['id' => 192, 'code' => 'SG', 'name' => 'Singapore'],
            ['id' => 193, 'code' => 'SK', 'name' => 'Slovakia'],
            ['id' => 194, 'code' => 'SI', 'name' => 'Slovenia'],
            ['id' => 195, 'code' => 'SB', 'name' => 'Solomon Islands'],
            ['id' => 196, 'code' => 'SO', 'name' => 'Somalia'],
            ['id' => 197, 'code' => 'ZA', 'name' => 'South Africa'],
            ['id' => 198, 'code' => 'GS', 'name' => 'South Georgia South Sandwich Islands'],
            ['id' => 199, 'code' => 'ES', 'name' => 'Spain'],
            ['id' => 200, 'code' => 'LK', 'name' => 'Sri Lanka'],
            ['id' => 201, 'code' => 'SH', 'name' => 'St. Helena'],
            ['id' => 202, 'code' => 'PM', 'name' => 'St. Pierre and Miquelon'],
            ['id' => 203, 'code' => 'SD', 'name' => 'Sudan'],
            ['id' => 204, 'code' => 'SR', 'name' => 'Suriname'],
            ['id' => 205, 'code' => 'SJ', 'name' => 'Svalbarn and Jan Mayen Islands'],
            ['id' => 206, 'code' => 'SZ', 'name' => 'Swaziland'],
            ['id' => 207, 'code' => 'SE', 'name' => 'Sweden'],
            ['id' => 208, 'code' => 'CH', 'name' => 'Switzerland'],
            ['id' => 209, 'code' => 'SY', 'name' => 'Syrian Arab Republic'],
            ['id' => 210, 'code' => 'TW', 'name' => 'Taiwan'],
            ['id' => 211, 'code' => 'TJ', 'name' => 'Tajikistan'],
            ['id' => 212, 'code' => 'TZ', 'name' => 'Tanzania, United Republic of'],
            ['id' => 213, 'code' => 'TH', 'name' => 'Thailand'],
            ['id' => 214, 'code' => 'TG', 'name' => 'Togo'],
            ['id' => 215, 'code' => 'TK', 'name' => 'Tokelau'],
            ['id' => 216, 'code' => 'TO', 'name' => 'Tonga'],
            ['id' => 217, 'code' => 'TT', 'name' => 'Trinidad and Tobago'],
            ['id' => 218, 'code' => 'TN', 'name' => 'Tunisia'],
            ['id' => 219, 'code' => 'TR', 'name' => 'Turkey'],
            ['id' => 220, 'code' => 'TM', 'name' => 'Turkmenistan'],
            ['id' => 221, 'code' => 'TC', 'name' => 'Turks and Caicos Islands'],
            ['id' => 222, 'code' => 'TV', 'name' => 'Tuvalu'],
            ['id' => 223, 'code' => 'UG', 'name' => 'Uganda'],
            ['id' => 224, 'code' => 'UA', 'name' => 'Ukraine'],
            ['id' => 225, 'code' => 'AE', 'name' => 'United Arab Emirates'],
            ['id' => 226, 'code' => 'GB', 'name' => 'United Kingdom'],
            ['id' => 227, 'code' => 'UM', 'name' => 'United States minor outlying islands'],
            ['id' => 228, 'code' => 'UY', 'name' => 'Uruguay'],
            ['id' => 229, 'code' => 'UZ', 'name' => 'Uzbekistan'],
            ['id' => 230, 'code' => 'VU', 'name' => 'Vanuatu'],
            ['id' => 231, 'code' => 'VA', 'name' => 'Vatican City State'],
            ['id' => 232, 'code' => 'VE', 'name' => 'Venezuela'],
            ['id' => 233, 'code' => 'VN', 'name' => 'Vietnam'],
            ['id' => 234, 'code' => 'VG', 'name' => 'Virgin Islands (British]'],
            ['id' => 235, 'code' => 'VI', 'name' => 'Virgin Islands (U.S.]'],
            ['id' => 236, 'code' => 'WF', 'name' => 'Wallis and Futuna Islands'],
            ['id' => 237, 'code' => 'EH', 'name' => 'Western Sahara'],
            ['id' => 238, 'code' => 'YE', 'name' => 'Yemen'],
            ['id' => 239, 'code' => 'YU', 'name' => 'Yugoslavia'],
            ['id' => 240, 'code' => 'ZR', 'name' => 'Zaire'],
            ['id' => 241, 'code' => 'ZM', 'name' => 'Zambia'],
            ['id' => 242, 'code' => 'ZW', 'name' => 'Zimbabwe'],
        ];

        DB::table('countries')->insert($countries);
    }
}
